# Machine-learning models in observables

Sometimes the mapping from model states to measurements may be only partially known or the dynamics of a system are otherwise hard to specify mechanistically. Both scenarios can be addressed by augmenting the observable formula in the PEtab problem with a neural network (NN).

This tutorial shows how to include an ML model in an observable formula using [AMICI](https://amici.readthedocs.io/en/latest/index.html) and focuses on the PEtab SciML files specific to this hybridization. It assumes familiarity with the [SciML starter tutorial](https://petab-sciml.readthedocs.io/latest/examples/getting_started/getting_started.html). This tutorial is also provided as a notebook, available [here](https://github.com/PEtab-dev/petab_sciml/blob/main/doc/examples/how_to_observable/how_to_observable.ipynb), and the corresponding PEtab SciML problem files can be downloaded [here](https://github.com/PEtab-dev/petab_sciml/tree/main/doc/examples/how_to_observable).

<figure style="text-align: center;">
  <img
    src="obs_hybrid.png"
    alt="Observable hybridization"
    class="only-light"
  />
  <img
    src="obs_hybrid_dark.png"
    alt="Observable hybridization"
    class="only-dark"
  />
</figure>

## Input problem

As a working example, the Lotka–Volterra system is considered:

$$
\begin{aligned}
\frac{\mathrm{d}\,\text{prey}}{\mathrm{d}t} &= \text{alpha} \cdot \text{prey}
- \text{beta} \cdot \text{prey} \cdot \text{predator}, \\
\frac{\mathrm{d}\,\text{predator}}{\mathrm{d}t} &= \text{gamma} \cdot \text{prey} \cdot \text{predator}
- \text{delta} \cdot \text{predator}.
\end{aligned}
$$

With observation model:

$$
\begin{aligned}
y_{\text{prey}} &= \text{prey} + \epsilon, \\
y_{\text{predator}} &= \text{predator} + \epsilon.
\end{aligned}
$$

where $\epsilon \sim \mathcal{N}(0, \sigma^2)$ is normally distributed measurement noise. To create the observable hybridization, the `prey` observable is replaced by a NN that takes the states `prey` and `predator` as input:

$$
y_{\text{prey}} = \mathrm{NN}(\text{prey}, \text{predator}; \text{theta})[0] + \epsilon.
$$

The `predator` observable is left unchanged. The goal of this tutorial is to set up a PEtab SciML problem for estimating both mechanistic parameters (`alpha`, `beta`, `gamma`, `delta`) and NN parameters (`theta`).

## Defining ML models in observable formulas

An ML model is used in an observable formula by  

1. Mapping the NN output to a PEtab identifier in the mapping table. 
2. Referencing that mapped output in the observables table
3. Specifying the NN inputs in the hybridization table.

To make this concrete, let's load the PEtab problem and inspect the relevant tables:

In [1]:
from amici.importers.petab import PetabImporter
from petab.v2 import Problem

# Load the PEtab problem information from disk.
petab_problem = Problem.from_yaml("problem.yaml")

# Create a simulator for the ODE and NN models.
petab_importer = PetabImporter(
    petab_problem, output_dir="model", compile_=True, jax=True
)

# The JAXProblem wraps the AMICI model together with the PEtab problem and
# handles additional simulation information (e.g. multiple experiments).
jax_problem = petab_importer.create_simulator()

The first step is to map the NN output to a valid PEtab identifier in the mapping table:

In [2]:
petab_problem.mapping_df

                    modelEntityId  name  index
petabEntityId
net1_input1     net1.inputs[0][0]  None      0
net1_input2     net1.inputs[0][1]  None      1
net1_output1   net1.outputs[0][0]  None      2
net1_ps           net1.parameters  None      3

The mapped output (`net1_output`) can then be referenced directly in the `observableFormula` column of the observables table:

In [3]:
petab_problem.observable_df

,observableName,observableFormula,noiseFormula,noiseDistribution,observablePlaceholders,noisePlaceholders
observableId,,,,,,
prey_o,None,net1_output1,0.0500000000000000,normal,,
predator_o,None,predator,0.0500000000000000,normal,,

Since the `prey` observable formula is defined by a PEtab identifier that represents a network output, it evaluates to the corresponding network value at each time point. While a simple formula is used here, more complex expressions are supported, for example `net1_output^2 + 2` or `net1_output + prey`.

In addition to the output, the network inputs must be specified. This is done in the hybridization table, where the input identifiers defined in the mapping table are assigned model quantities, here the states `prey` and `predator`:

In [4]:
petab_problem.extensions.sciml.hybridization_df

      targetId targetValue
0  net1_input1        prey
1  net1_input2    predator

Lastly, since the neural network is evaluated during simulation (its output depends on the ODE solution), it must be listed in the problem YAML with `pre_initialization = false`. Concretely, the SciML section of `problem.yaml` should look like:

```yaml
extensions:
  sciml:
    version: 0.1.0
    required: true
    neural_networks:
      net1:
        location: "net1.yaml"
        pre_initialization: false
        format: "YAML"
    array_files:
      - "net1_ps.hdf5" # neural network parameters
    hybridization_files:
      - "hybridization.tsv"
```