# Machine-learning models in observables

Mechanistic models can be misspecified, or the mapping from model states to measurements may be only partially known. Both scenarios can be addressed by augmenting the observable formula in the PEtab problem with a neural network.

This tutorial shows how to include an ML model in an observable formula and focuses on the PEtab-SciML files specific to this hybridization. It assumes familiarity with the [SciML starter tutorial](https://petab-sciml.readthedocs.io/latest/examples/getting_started/getting_started.html). This tutorial is also provided as a notebook, available [here](https://github.com/PEtab-dev/petab_sciml/blob/main/doc/examples/how_to_observable/how_to_observable.ipynb), and the corresponding PEtab-SciML problem files can be downloaded [here](https://github.com/PEtab-dev/petab_sciml/tree/main/doc/examples/how_to_observable).

## Input problem

As a running example, we use the Lotka–Volterra system:

$$
\begin{aligned}
\frac{\mathrm{d}\,\text{prey}}{\mathrm{d}t} &= \alpha \cdot \text{prey}
- \beta \cdot \text{prey} \cdot \text{predator}, \\
\frac{\mathrm{d}\,\text{predator}}{\mathrm{d}t} &= \gamma \cdot \text{prey} \cdot \text{predator}
- \delta \cdot \text{predator}.
\end{aligned}
$$

With observation model:

$$
\begin{aligned}
y_{\text{prey}} &= \text{prey} + \epsilon, \\
y_{\text{predator}} &= \text{predator} + \epsilon.
\end{aligned}
$$

In this example, the `prey` observable is replaced by a neural network that takes the states `prey` and `predator` as input:

$$
y_{\text{prey}} = \mathrm{NN}(\text{prey}, \text{predator}; \theta)[0] + \epsilon.
$$

The `predator` observable is left unchanged.

## Defining ML models in observable formulas

An ML model is used in an observable formula by (1) mapping the neural-network output to a PEtab identifier in the mapping table, (2) referencing that mapped output in the observables table, and (3) specifying the neural-network inputs in the hybridization table.

To make this concrete, let's load the PEtab problem and inspect the relevant tables:

In [ ]:
from amici.petab import import_petab_problem
from amici.jax import JAXProblem
from petab.v2 import Problem

# Load the PEtab problem information from disk.
petab_problem = Problem.from_yaml("problem.yaml")

# Create a simulator for the ODE and NN models.
jax_model = import_petab_problem(
    petab_problem, model_output_dir="model", compile_=True, jax=True
)

# Create a JAXProblem to handle addition simulation information
# (e.g. simulate multiple conditions).
jax_problem = JAXProblem(jax_model, petab_problem)

The first step is to map the neural-network output to a valid PEtab identifier in the mapping table:

In [19]:
petab_problem.mapping_df

                    modelEntityId
petabEntityId
net1_input1     net1.inputs[0][0]
net1_input2     net1.inputs[0][1]
net1_output1   net1.outputs[0][0]
net1_ps           net1.parameters

The mapped output (`net1_output`) can then be referenced directly in the observableFormula column of the observables table:

In [20]:
petab_problem.observable_df

,observableFormula,noiseFormula,observableTransformation,noiseDistribution
observableId,,,,
prey_o,net1_output1,0.05,lin,normal
predator_o,predator,0.05,lin,normal

Here, the prey observable formula is defined by a PEtab identifier that represents a network output. In this example the formula is simple, but arbitrary expressions are supported, for example `net1_output^2 + 2` or `net1_output + prey`.

In addition to the output, the network inputs must be specified. This is done in the hybridization table, where the input identifiers defined in the mapping table are assigned model quantities, here the states `prey` and `predator`:

In [21]:
# TODO: Fix when AMICI is updated
import pandas as pd

hybridization_df = pd.read_csv("hybridization.tsv", sep="\t")
hybridization_df

      targetId targetValue
0  net1_input1        prey
1  net1_input2    predator

Lastly, importantly as the neural network is evaluated dynamically (its values depends on computed ODE solution), in the problem YAML file the neural network must be specifed with `pre_initialization = false`.