# Pre-simulation machine-learning models

Sometimes informative high dimensional non-time-series data (e.g. images, omics data) are available. One way to leverage such data is to use a machine-learning (ML) model that takes it as input and, before simulation, maps it to ODE parameters and/or initial conditions.

This tutorial shows how to define SciML problems where an ML model is evaluated pre-simulation to set model parameters using [AMICI](https://amici.readthedocs.io/en/latest/index.html). It focuses on the PEtab-SciML files specific to this hybridization and covers the case where the ML model takes array inputs that vary across PEtab conditions. Familiarity with the [SciML starter tutorial](https://petab-sciml.readthedocs.io/latest/examples/getting_started/getting_started.html) is assumed. The tutorial is provided as a notebook, available [here](https://github.com/PEtab-dev/petab_sciml/blob/main/doc/examples/how_to_dmms/how_to_dmms.ipynb), and the corresponding PEtab-SciML problem files can be downloaded [here](https://github.com/PEtab-dev/petab_sciml/tree/main/doc/examples/how_to_dmms).

## Input problem

As a running example, the Lotka–Volterra system is considered:

$$
\begin{aligned}
\frac{\mathrm{d}\,\text{prey}}{\mathrm{d}t} &= \alpha \cdot \text{prey}
- \beta \cdot \text{prey} \cdot \text{predator}, \\
\frac{\mathrm{d}\,\text{predator}}{\mathrm{d}t} &= \gamma \cdot \text{prey} \cdot \text{predator}
- \delta \cdot \text{predator}.
\end{aligned}
$$

With observation model:

$$
\begin{aligned}
y_{\text{prey}} &= \text{prey} + \epsilon, \\
y_{\text{predator}} &= \text{predator} + \epsilon.
\end{aligned}
$$

In this example, a neural network evaluated prior to simulation sets the value of the model parameter `gamma`. The ODE system becomes:

$$
\begin{aligned}
\frac{\mathrm{d}\,\text{prey}}{\mathrm{d}t} &= \alpha \cdot \text{prey}
- \beta \cdot \text{prey} \cdot \text{predator}, \\
\frac{\mathrm{d}\,\text{predator}}{\mathrm{d}t} &= \mathrm{NN}(\cdot; \theta)[0] \cdot \text{prey} \cdot \text{predator}
- \delta \cdot \text{predator}.
\end{aligned}
$$

where $\mathrm{NN}(\cdot; \theta)$ denotes a neural network that takes array (tensor) inputs whose values vary across PEtab simulation conditions. The goal of this tutorial is to set up a PEtab-SciML problem for estimating both mechanistic parameters (`alpha`, `beta`, `delta`) and neural-network parameters (`theta`).

## Defining a pre-simulation SciML problem

A pre-simulation SciML problem with array inputs is defined by:

1. Mapping neural-network inputs and outputs to PEtab identifiers in the mapping table.
2. Assigning the network output to a model parameter (or initial condition) in the hybridization table.
3. Providing condition-specific input arrays in a PEtab-SciML HDF5 array file.
4. Setting the network to be evaluated pre-initialization in the problem YAML.

To make this concrete, let's load the PEtab problem and inspect the relevant tables:

In [ ]:
from amici.petab import import_petab_problem
from amici.jax import (
    JAXProblem,
)
from petab.v2 import Problem

# Load the PEtab problem information from disk.
petab_problem = Problem.from_yaml("problem.yaml")

# Create a simulator for the ODE and NN models.
jax_model = import_petab_problem(
    petab_problem, model_output_dir="model", compile_=True, jax=True
)

# Create a JAXProblem to handle addition simulation information
# (e.g. simulate multiple conditions).
jax_problem = JAXProblem(jax_model, petab_problem)

### Mapping and hybridization tables

First, we inspect the mapping and hybridization tables:

In [2]:
petab_problem.mapping_df

                    modelEntityId
petabEntityId
input0             net3.inputs[0]
net3_output1   net3.outputs[0][0]
net3_ps           net3.parameters

In [3]:
# TODO: Fix when AMICI is updated
import pandas as pd

hybridization_df = pd.read_csv("hybridization.tsv", sep="\t")
hybridization_df

  targetId   targetValue
0    gamma  net3_output1

From the hybridization table, the network output is mapped to the model parameter `gamma`. During import, this means that `gamma` is provided by the neural-network output. The network input `input0` is mapped to `net3.inputs[0]`. Note that no additional indexing into the input argument is used here, since the full input tensor is provided via an array input file (see section below).

Finally, since `gamma` is assigned by the neural network, it should not appear as an estimated parameter in the parameters table.

In [4]:
petab_problem.parameter_df

            parameterScale  lowerBound  upperBound  nominalValue  estimate
parameterId
alpha                  lin         0.0        15.0           1.3         1
delta                  lin         0.0        15.0           1.8         1
beta                   lin         0.0        15.0           0.9         1
net3_ps                lin        -inf         inf           NaN         1

### Neural network input array data

Neural network input array data should be provided in the PEtab-SciML HDF5-array format, with the following structure:

```text
arrays.hdf5
├── metadata
│   └── pytorch_format
└── inputs
    └── inputId
        ├── conditionId1
        └── conditionId2
```

Here, `inputId` links a PEtab identifier to condition-specific array data. For our working example, `inputId` is `input0` as defined in the mapping table, and `pytorch_format = true`, as the arrays follow PyTorch indexing conventions. Assuming two PEtab conditions, `cond1` and `cond2`, input data in this format can be generated using helper functions from the `petab_sciml` library:

In [5]:
import numpy as np
from petab_sciml.standard.array_data import ArrayData, ArrayDataStandard

# Generate random condition-specific neural network input arrays
# for illustration
input_cond1 = np.random.rand(1, 3, 10, 10)
input_cond2 = np.random.rand(1, 3, 10, 10)

# Define the array data using the PEtab-SciML HDF5-array structure.
data = {
    "metadata": {"pytorch_format": True},
    "inputs": {"inputId1": {"cond1": input_cond1, "cond2": input_cond2}},
}

# Export the data to PEtab-SciML HDF5 format
array_data = ArrayData.model_validate(data)
ArrayDataStandard.save_data(array_data, filename="input_data.hdf5")

When defining condition-specific inputs, the corresponding conditions must also be defined in the condition table and linked to experiments table.  In our example, valid condition and experiment tables are:

In [6]:
petab_problem.condition_df

Empty DataFrame
Columns: []
Index: [cond1, cond2]

In [7]:
# TODO: When AMICI updated, add experiment table

### YAML problem file

For problems with array-based inputs, `problem.yaml` should list the relevant array files (for both network inputs and network parameters). Since the neural network is evaluated pre-simulation in this example, `pre_initialization` must be set to `true`. For this problem, the PEtab-SciML extension section therefore is:

```yaml
extensions:
  sciml:
    version: 0.1.0
    required: true
    neural_nets:
      net1:
        location: "net3.yaml"
        pre_initialization: true
        format: "YAML"
    array_files:
      - "net3_ps.hdf5"      # Parameter values
      - "input_data.hdf5"   # Input data
    hybridization_files:
      - "hybridization.tsv"
```

### Neural network architecture

For completeness, the snippet below shows how the neural network architecture used in this problem is defined and exported. A convolutional architecture was used to illustrate how PEtab-SciML can map high-dimensional data to a mechanistic model.

In [8]:
from petab_sciml.standard.nn_model import Input, NNModel, NNModelStandard
import torch
from torch import nn
import torch.nn.functional as F


class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Conv2d(
            3, 1, (5, 5), stride=(1, 1), padding=(0, 0), dilation=(1, 1)
        )
        self.layer2 = torch.nn.Flatten()
        self.layer3 = torch.nn.Linear(36, 1)

    def forward(self, net_input):
        x = self.layer1(net_input)
        x = self.layer2(x)
        x = self.layer3(x)
        x = F.relu(x)
        return x


net1 = NeuralNetwork()
nn_model1 = NNModel.from_pytorch_module(
    module=net1, nn_model_id="net3", inputs=[Input(input_id="input0")]
)
NNModelStandard.save_data(data=nn_model1, filename="net3_from_pytorch.yaml")

### Parameterizing network inputs

A straightforward alternative to defining network inputs as array data in files, is to define them in the parameters table, with appropriate bounds and nominal values. 

| parameterId     | parameterScale | lowerBound | upperBound | nominalValue | estimate |
|-----------------|----------------|------------|------------|--------------|----------|
| net1_input_pre1 | lin            | -inf       | inf        | 1            | 0        |
| net1_input_pre2 | lin            | -inf       | inf        | 1            | 0        |
|                 |                |            |            |              |          |

The network inputs can be defined as condition specific, with different scalar values for different conditions.

| conditionId     | net1_input1       | net1_input2       |
|-----------------|-------------------|-------------------|
| cond1           | 10.0              | 20.0              |
| cond2           | net1_input_pre1   | net1_input_pre2   |

The corresponding mapping table then defines the model entities for condition PEtab identifiers.

| petabEntityId   | modelEntityId     |
|-----------------|-------------------|
| net1_input1     | net1.inputs[0][0] |
| net1_input2     | net1.inputs[0][1] |